import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: { padding: 20, gap: 16, paddingBottom: 40 },
  greetingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  greeting: { color: colors.text, fontSize: 23, fontWeight: '800' },
  date: { color: colors.textMuted, fontSize: 14, marginTop: 4 },
  alertBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(226,168,62,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(226,168,62,0.3)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  alertBadgeText: { color: colors.warning, fontSize: 13, fontWeight: '600' },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 16,
    padding: 16,
  },
  cardLabel: { color: colors.textMuted, fontSize: 13, letterSpacing: 1 },
  cardBigNumber: { color: colors.text, fontSize: 28, fontWeight: '800', marginTop: 6 },
  cardSubtext: { color: colors.textMuted, fontSize: 15, marginTop: 4 },
  cardSubtextGreen: { color: colors.success, fontWeight: '700' },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: { color: colors.text, fontSize: 18, fontWeight: '700' },
  cardTitleMuted: { color: colors.textMuted, fontSize: 14 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 12,
  },
  rowIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(159,18,20,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowTime: { color: colors.primary, fontSize: 15, fontWeight: '700', width: 48 },
  rowName: { color: colors.text, fontSize: 15, fontWeight: '600' },
  rowSubtitle: { color: colors.textMuted, fontSize: 14, marginTop: 2 },
  divider: { height: 1, backgroundColor: colors.cardBorder },
  dot: { width: 8, height: 8, borderRadius: 4 },
  badge: {
    backgroundColor: 'rgba(226,168,62,0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: { color: colors.warning, fontSize: 14, fontWeight: '700' },
  avatarCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  rightText: { alignItems: 'flex-end' },
  valueText: { color: colors.text, fontSize: 14, fontWeight: '700' },

  // Gráfico de faturamento mensal
  chartLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 36,
    marginTop: 4,
  },
  chartAxisLabel: { color: colors.textMuted, fontSize: 12 },
  chartTooltip: {
  position: 'absolute',
  backgroundColor: colors.card,
  borderWidth: 1,
  borderColor: colors.cardBorder,
  borderRadius: 10,
  paddingHorizontal: 10,
  paddingVertical: 8,
  minWidth: 150,
  // sombra leve pra destacar do fundo do gráfico
  shadowColor: '#000',
  shadowOpacity: 0.3,
  shadowRadius: 6,
  shadowOffset: { width: 0, height: 2 },
  elevation: 4,
},
chartTooltipHeaderRow: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 6,
},
chartTooltipDot: {
  width: 6,
  height: 6,
  borderRadius: 3,
  backgroundColor: colors.primary,
},
chartTooltipMonth: { color: colors.text, fontSize: 12, fontWeight: '700' },
chartTooltipValue: { color: colors.text, fontSize: 12, marginTop: 4 },
});