import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: { padding: 20, gap: 16, paddingBottom: 40 },
  greetingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  greeting: { color: colors.text, fontSize: 20, fontWeight: '800' },
  date: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  alertBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(226,168,62,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(226,168,62,0.3)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  alertBadgeText: { color: colors.warning, fontSize: 11, fontWeight: '600' },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 16,
    padding: 16,
  },
  cardLabel: { color: colors.textMuted, fontSize: 11, letterSpacing: 1 },
  cardBigNumber: { color: colors.text, fontSize: 24, fontWeight: '800', marginTop: 6 },
  cardSubtext: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  cardSubtextGreen: { color: colors.success, fontWeight: '700' },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
  cardTitleMuted: { color: colors.textMuted, fontSize: 11 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 12,
  },
  rowIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(159,18,20,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowTime: { color: colors.primary, fontSize: 12, fontWeight: '700', width: 44 },
  rowName: { color: colors.text, fontSize: 13, fontWeight: '600' },
  rowSubtitle: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  divider: { height: 1, backgroundColor: colors.cardBorder },
  dot: { width: 8, height: 8, borderRadius: 4 },
  badge: {
    backgroundColor: 'rgba(226,168,62,0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: { color: colors.warning, fontSize: 10, fontWeight: '700' },
  avatarCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  rightText: { alignItems: 'flex-end' },
  valueText: { color: colors.text, fontSize: 12, fontWeight: '700' },
});