import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, borderColor: colors.cardBorder, borderWidth: 1 },
  flashScrollContent: { paddingHorizontal: 20, paddingBottom: 30 },
  flashHeader: { marginTop: 12, marginBottom: 20 },
  flashHint: { color: colors.textMuted, fontSize: 13, marginTop: 3 },
  scrollContent: { padding: 20, gap: 16, paddingBottom: 40 },
  flashGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingBottom: 30,
  },
  flashCard: {
    width: '48%',
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 16,
    backgroundColor: colors.card,
  },
  flashCardImage: {
    aspectRatio: 1,
    backgroundColor: '#252222',
    position: 'relative',
    overflow: 'hidden',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  flashCardPhoto: {
    ...StyleSheet.absoluteFillObject,
  },
  flashCardPrice: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    position: 'absolute',
    right: 8,
    bottom: 8,
    zIndex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 2,
  },
  flashCardContent: { padding: 10, minHeight: 52 },
  flashCardName: { color: colors.text, fontSize: 14, fontWeight: '700' },
  flashCardDetail: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  flashImage: {
    height: 160,
    borderRadius: 12,
    backgroundColor: colors.cardBorder,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flashImageText: { color: colors.textMuted, fontSize: 16, fontWeight: '700' },
  flashInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  greetingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  greeting: { color: colors.text, fontSize: 24, fontWeight: '800' },
  date: { color: colors.textMuted, fontSize: 14, marginTop: 4 },
  alertBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(226,168,62,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(226,168,62,0.3)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  alertBadgeText: { color: colors.warning, fontSize: 13, fontWeight: '600' },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 16,
    padding: 16,
  },
  cardLabel: { color: colors.textMuted, fontSize: 12, letterSpacing: 1 },
  cardBigNumber: { color: colors.text, fontSize: 24, fontWeight: '800', marginTop: 6 },
  cardSubtext: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  cardSubtextGreen: { color: colors.success, fontWeight: '700' },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
  cardTitleMuted: { color: colors.textMuted, fontSize: 11 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 12,
  },
  rowIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(159,18,20,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowTime: { color: colors.primary, fontSize: 12, fontWeight: '700', width: 44 },
  rowName: { color: colors.text, fontSize: 13, fontWeight: '600' },
  rowSubtitle: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  divider: { height: 1, backgroundColor: colors.cardBorder },
  dot: { width: 8, height: 8, borderRadius: 4 },
  badge: {
    backgroundColor: 'rgba(226,168,62,0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: { color: colors.warning, fontSize: 10, fontWeight: '700' },
  avatarCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  rightText: { alignItems: 'flex-end' },
  valueText: { color: colors.text, fontSize: 12, fontWeight: '700' },

  flashCardAdd: {
    width: '48%',
    marginBottom: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.cardBorder,
    borderRadius: 16,
    minHeight: 180,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.card,
  },
  flashCardAddText: { color: colors.textMuted, fontSize: 13, fontWeight: '600', marginTop: 8 },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: colors.card,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  modalImageWrapper: { width: '100%', height: 220, backgroundColor: '#252222' },
  modalCloseButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCodeBadge: {
    position: 'absolute',
    left: 12,
    bottom: 12,
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  modalCodeText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  modalContent: { padding: 20 },
  modalHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  modalName: { color: colors.text, fontSize: 20, fontWeight: '800' },
  modalDetail: { color: colors.primary, fontSize: 13, fontWeight: '600', marginTop: 2 },
  modalPrice: { color: colors.primary, fontSize: 22, fontWeight: '800' },
  modalDescription: { color: colors.textMuted, fontSize: 13, marginTop: 16, lineHeight: 19 },
  modalEditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    marginTop: 20,
  },
  modalEditButtonText: { color: colors.text, fontSize: 14, fontWeight: '700' },

    imagePickerBox: {
    height: 160,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.cardBorder,
    backgroundColor: colors.input,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  imagePickerPreview: { width: '100%', height: '100%' },
  imagePickerText: { color: colors.textMuted, fontSize: 13, marginTop: 6 },
  modalInput: {
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 14,
    marginBottom: 12,
  },
  modalInputMultiline: { minHeight: 80, textAlignVertical: 'top' },
});