import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

const fundo = '#0F0808';
const superficie = 'rgba(255,255,255,0.03)';
const borda = '#3B2424';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: fundo },
  bordaCabecalho: { borderBottomWidth: 1, borderBottomColor: borda },
  conteudo: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 40 },
  titulo: { color: colors.text, fontSize: 24, fontWeight: '700' },
  subtitulo: { color: colors.textMuted, fontSize: 13, marginTop: 5 },
  cartaoPerfil: {
    alignItems: 'center',
    backgroundColor: superficie,
    borderColor: borda,
    borderWidth: 1,
    borderRadius: 16,
    padding: 24,
    marginTop: 18,
  },
  botaoAvatar: { position: 'relative' },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primaryDark,
    borderColor: colors.primary,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconeCamera: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: superficie,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inicial: { color: colors.text, fontSize: 28, fontWeight: '700' },
  nome: { color: colors.text, fontSize: 20, fontWeight: '700', marginTop: 13 },
  tipoConta: { color: colors.textMuted, fontSize: 14, marginTop: 4 },
  cartaoDados: {
    backgroundColor: superficie,
    borderColor: borda,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
  },
  cartaoAcoes: {
    backgroundColor: superficie,
    borderColor: borda,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
  },
  tituloSecao: { color: colors.text, fontSize: 16, fontWeight: '700', marginBottom: 6 },
  campo: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14 },
  iconeCampo: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: 'rgba(159,18,20,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textosCampo: { flex: 1, gap: 4 },
  rotuloCampo: { color: colors.textMuted, fontSize: 12, letterSpacing: 0.8 },
  valorCampo: { color: colors.text, fontSize: 13, fontWeight: '600' },
  divisor: { height: 1, backgroundColor: borda },
  opcao: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14 },
  tituloOpcao: { color: colors.text, fontSize: 13, fontWeight: '600' },
  descricaoOpcao: { color: colors.textMuted, fontSize: 13, marginTop: 4 },
  removerFoto: { paddingLeft: 46, paddingBottom: 13 },
  textoRemoverFoto: { color: '#E48787', fontSize: 12, fontWeight: '600' },
  botaoSair: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primaryDark,
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 14,
    minHeight: 48,
    marginTop: 20,
  },
  textoSair: { color: colors.text, fontSize: 13, fontWeight: '700' },
});
