import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, paddingBottom: 40, gap: 16 },
  backButton: { flexDirection: 'row', alignItems: 'center', gap: 8, alignSelf: 'flex-start' },
  backText: { color: colors.textMuted, fontSize: 13, fontWeight: '600' },
  title: { color: colors.text, fontSize: 24, fontWeight: '800', marginTop: 4 },
  subtitle: { color: colors.textMuted, fontSize: 14, marginTop: -10 },
  section: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 16,
    padding: 16,
    gap: 10,
  },
  sectionTitle: { color: colors.text, fontSize: 15, fontWeight: '800' },
  materialGroup: { gap: 6 },
  materialRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  materialSelect: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 11,
    backgroundColor: colors.input,
    paddingHorizontal: 12,
  },
  selectText: { color: colors.text, fontSize: 14, flex: 1 },
  selectPlaceholder: { color: colors.textPlaceholder, fontSize: 14, flex: 1 },
  quantityInput: {
    width: 72,
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 11,
    backgroundColor: colors.input,
    color: colors.text,
    paddingHorizontal: 10,
    fontSize: 14,
    textAlign: 'center',
  },
  input: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 11,
    backgroundColor: colors.input,
    color: colors.text,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  unitText: { color: colors.textMuted, fontSize: 12, marginLeft: 4 },
  dropdownList: {
    maxHeight: 190,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 11,
    backgroundColor: '#241212',
  },
  dropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  dropdownOptionText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  dropdownOptionUnit: { color: colors.textMuted, fontSize: 11, marginTop: 3 },
  removeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(255,90,95,0.1)',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderStyle: 'dashed',
  },
  addButtonText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  paymentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  paymentOption: {
    minWidth: '47%',
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 10,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.input,
  },
  paymentOptionActive: { backgroundColor: 'rgba(159,18,20,0.3)', borderColor: colors.primary },
  paymentText: { color: colors.textMuted, fontSize: 13, fontWeight: '700' },
  paymentTextActive: { color: colors.text },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: colors.primary,
  },
  submitText: { color: '#fff', fontSize: 14, fontWeight: '800' },
});
