import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalBox: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#1a0a0b',
    borderWidth: 1,
    borderColor: 'rgba(159,18,20,0.4)',
    borderRadius: 20,
    padding: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: { flexDirection: 'row', gap: 12, flex: 1 },
  headerIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(23, 166, 171, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  headerSubtitle: { color: colors.textMuted, fontSize: 11, marginTop: 2, letterSpacing: 0.5 },

  stepsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  stepItem: { alignItems: 'center', width: 56 },
  stepCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#00D3F2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: { borderColor: '#00D3F2', backgroundColor: 'rgba(23, 166, 171, 0.3)' },
  stepNumber: { color: '#00D3F2', fontSize: 13, fontWeight: '700' },
  stepNumberActive: { color: '#00D3F2' },
  stepLabel: { color: '#00D3F2', fontSize: 11, marginTop: 6 },
  stepLine: { flex: 1, height: 1, backgroundColor: '#00D3F2', marginBottom: 20 },

  uploadArea: {
    marginTop: 20,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#00D3F2',
    borderRadius: 14,
    paddingVertical: 32,
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 6,
  },
  uploadTitle: { color: colors.text, fontSize: 14, fontWeight: '700', marginTop: 6 },
  uploadSubtitle: { color: colors.textMuted, fontSize: 12, textAlign: 'center' },
  uploadHint: { color: colors.textMuted, fontSize: 10, marginTop: 8, fontStyle: 'italic' },
  previewImage: { width: '100%', height: 160, borderRadius: 8 },

  errorText: { color: '#ff6b6b', fontSize: 12, marginTop: 12, textAlign: 'center' },

  startButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(23, 166, 171, 0.3)',
    borderWidth: 1,
    borderColor: '#00D3F2',
    borderRadius: 12,
    paddingVertical: 14,
    marginTop: 20,
  },
  startButtonDisabled: { opacity: 0.6 },
  startButtonText: { color: '#00D3F2', fontSize: 14, fontWeight: '700' },
});