import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.78)', justifyContent: 'center', alignItems: 'center', padding: 16 },
  modalBox: { width: '100%', maxWidth: 500, maxHeight: '92%', backgroundColor: '#1a0a0b', borderWidth: 1, borderColor: 'rgba(159,18,20,0.4)', borderRadius: 20, padding: 18 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  headerLeft: { flexDirection: 'row', gap: 12, flex: 1 },
  headerText: { flex: 1 },
  headerIconBox: { width: 36, height: 36, borderRadius: 10, backgroundColor: 'rgba(23,166,171,0.3)', justifyContent: 'center', alignItems: 'center' },
  headerTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  headerSubtitle: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  content: { paddingTop: 14, paddingBottom: 8, gap: 10 },
  uploadArea: { borderWidth: 1, borderStyle: 'dashed', borderColor: '#00D3F2', borderRadius: 14, minHeight: 160, padding: 16, justifyContent: 'center', alignItems: 'center', gap: 6 },
  previewImage: { width: '100%', height: 190, borderRadius: 8 },
  uploadTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
  uploadSubtitle: { color: colors.textMuted, fontSize: 12, textAlign: 'center' },
  actionRow: { flexDirection: 'row', gap: 10 },
  secondaryButton: { flex: 1, borderWidth: 1, borderColor: '#00D3F2', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 12, alignItems: 'center' },
  secondaryText: { color: '#00D3F2', fontSize: 13, fontWeight: '700' },
  label: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  input: { color: colors.text, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 9, fontSize: 14, minHeight: 42 },
  link: { color: '#00D3F2', fontSize: 12, textDecorationLine: 'underline' },
  notice: { color: colors.textMuted, fontSize: 12, lineHeight: 18 },
  sectionTitle: { color: colors.text, fontSize: 15, fontWeight: '700', marginTop: 4 },
  itemCard: { borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.card, borderRadius: 12, padding: 12, gap: 8 },
  itemHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  itemTitle: { color: colors.text, fontSize: 13, fontWeight: '700' },
  removeText: { color: '#ff7878', fontSize: 12 },
  fieldRow: { flexDirection: 'row', gap: 7 },
  field: { flex: 1, gap: 6 },
  ocrText: { color: colors.textMuted, fontSize: 11, lineHeight: 16, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 8, padding: 10 },
  errorText: { color: '#ff7878', fontSize: 12 },
  startButton: { alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(23,166,171,0.3)', borderWidth: 1, borderColor: '#00D3F2', borderRadius: 12, paddingVertical: 14, marginTop: 4 },
  startButtonDisabled: { opacity: 0.6 },
  startButtonText: { color: '#00D3F2', fontSize: 14, fontWeight: '700' },
});
