import { Platform, StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

const fundo = '#1A1313';
const superficie = '#211717';
const borda = '#3B2424';
const mono = Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' });

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: fundo },
  headerBorder: { borderBottomWidth: 1, borderBottomColor: borda },
  conteudo: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 40, gap: 16 },
  titulo: { color: colors.text, fontSize: 16, fontWeight: '700' },
  textoSecundario: { color: colors.textMuted, fontSize: 11 },
  perfil: {
    backgroundColor: superficie,
    borderColor: borda,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
  },
  cabecalhoPerfil: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primaryDark,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iniciais: { color: colors.text, fontSize: 15, fontWeight: '700' },
  identificacao: { flex: 1, gap: 4 },
  nome: { color: colors.text, fontSize: 18, fontWeight: '700' },
  estilos: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 14 },
  etiquetaEstilo: {
    backgroundColor: 'rgba(159,18,20,0.18)',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  textoEstilo: { color: '#E48787', fontSize: 10 },
  indicadores: { flexDirection: 'row', gap: 8 },
  indicador: {
    flex: 1,
    minWidth: 0,
    height: 75,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: superficie,
    borderColor: borda,
    borderWidth: 1,
    borderRadius: 14,
    gap: 8,
  },
  indicadorTitulo: {
    color: colors.textMuted,
    fontFamily: mono,
    fontSize: 9,
    textAlign: 'center',
  },
  indicadorValor: { color: colors.text, fontSize: 15, fontWeight: '700', textAlign: 'center', width: '100%' },
  cabecalhoLista: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginTop: 4 },
  tituloLista: { color: colors.text, fontSize: 15, fontWeight: '700' },
  cartaoSessao: {
    backgroundColor: superficie,
    borderColor: borda,
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
  },
  linhaSessao: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  numeroSessao: { color: colors.textMuted, fontFamily: mono, fontSize: 10, letterSpacing: 0.8 },
  dataSessao: { color: colors.textMuted, fontSize: 11 },
  procedimento: { color: colors.text, fontSize: 14, fontWeight: '700', marginTop: 11 },
  metadados: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8, marginTop: 8 },
  duracao: { color: colors.textMuted, fontSize: 11 },
  divisor: { height: 1, backgroundColor: borda, marginTop: 14, marginBottom: 11 },
  linhaValor: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  rotuloValor: { color: colors.textMuted, fontFamily: mono, fontSize: 9, letterSpacing: 0.5 },
  valorSessao: { color: colors.text, fontSize: 12, fontWeight: '700' },
});
