import { Platform, StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

const monoFont = Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' });
const surface = 'rgba(255,255,255,0.03)';
const border = 'rgba(255,255,255,0.08)';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F0808' },
  headerBorder: { borderBottomWidth: 1, borderBottomColor: border },
  content: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 40 },
  title: { color: colors.text, fontSize: 24, fontWeight: '700' },
  subtitle: { color: colors.textMuted, fontSize: 13, marginTop: 5 },
  searchInput: {
    height: 32,
    marginTop: 14,
    paddingHorizontal: 13,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#281919',
    color: colors.text,
    fontSize: 13,
  },
  statsRow: { flexDirection: 'row', gap: 8, marginTop: 18 },
  statCard: {
    flex: 1,
    minWidth: 0,
    height: 92,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: surface,
  },
  statLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: monoFont,
    textAlign: 'center',
    lineHeight: 12,
    minHeight: 25,
  },
  statValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 5,
    width: '100%',
    lineHeight: 22,
  },
  tableFrame: {
    marginTop: 16,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: surface,
    overflow: 'hidden',
  },
  tableHeader: {
    height: 43,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  columnHeading: {
    color: colors.textMuted,
    fontSize: 10,
    fontFamily: monoFont,
    letterSpacing: 0.8,
  },
  tableRow: {
    minHeight: 55,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  lastRow: { borderBottomWidth: 0 },
  rowPressed: { backgroundColor: 'rgba(159,18,20,0.13)' },
  clientCell: { width: 67, paddingLeft: 16, justifyContent: 'center' },
  sessionsCell: { width: 65, textAlign: 'center' },
  spentCell: { width: 83, textAlign: 'center' },
  lastSessionCell: { width: 60, textAlign: 'center' },
  stylesCell: { width: 123, paddingHorizontal: 8, alignItems: 'flex-start', justifyContent: 'center' },
  clientAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primaryDark,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clientInitials: { color: colors.text, fontSize: 12, fontWeight: '700' },
  cellText: { color: colors.text, fontSize: 13 },
  spentCellText: { fontFamily: monoFont },
  styleBadge: {
    backgroundColor: 'rgba(159,18,20,0.18)',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginVertical: 1,
  },
  styleBadgeText: { color: '#E48787', fontSize: 10 },
  emptyText: { color: colors.textMuted, fontSize: 12, padding: 20 },
});
